### ISSUE TITLE
pcl::IOException Error

### ISSUE THREAD

**Issue by jdkanani** [PaulBernier/obj2pcd#1]
I am getting following error while converting obj to pcd:

```
terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinaryCompressed] Error during mmap ()!
Aborted
```

Any thoughts?

**Comment by PaulBernier** [comment]
Hi, can you provide your .obj file? As far as I remember the program handles only very basic obj files (that contains only coordinates) so it's very likely the problem.

**Comment by jdkanani** [comment]
It seems any pcd file has this problem. Just pick any pcd file like [this](https://github.com/PointCloudLibrary/data/blob/master/biwi_face_database/model.pcd), convert it to obj file and try convert it back to pcd file.

**Comment by PaulBernier** [comment]
I couldn't reproduce the error. I converted the model.pcd to obj with `obj2pcd -p2o model.pcd`. Then I converted back the output.obj to pcd file with `obj2pcd -o2p output.obj` and I got a output.pcd identical to the original model.pcd.
Regarding your error you may try to replace the call to `pcl::io::savePCDFileBinaryCompressed` by `pcl::io::savePCDFile` in the source code and try if you get also an error.

**Comment by jdkanani** [comment]
changed to `pcl::io::savePCDFile` and it worked.
