### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by JidaHuang** [PaulBernier/obj2pcd#4]
Hi,

I'm new to PCL, so when I use this converter, build error like this:
LINK : fatal error LNK1104: cannot open file 'boost_system.lib'

How can I fix this?

**Comment by PaulBernier** [comment]
Hi,
What version of PCL did you installed?
Do you have boost installed on your computer too? http://www.boost.org/users/download/
You may need to change the CMakeList.txt file to fit your system configuration.

**Comment by JidaHuang** [comment]
thanks a lot, it works now!
