### ISSUE TITLE
How to install this on windows machine ?

### ISSUE THREAD

**Issue by jay-thakur** [PaulBernier/obj2pcd#6]
Hi,

I have cloned this repo. I am new to C++. Could you please guide me how to install this? 

how to get the folder obj2pcd ? after cloning this.

I have build it & i can see .sln file.

Please help/guide.

Thanks,
Jay

**Comment by PaulBernier** [comment]
The source code needs to be compiled into an executable. This project uses CMake to build the project, you can search on the official website how to install and run CMake on the project: https://cmake.org/runningcmake/ In the end you will get a obj2pcd.exe if successful.

**Comment by jay-thakur** [comment]
@PaulBernier Thank you so much. its working now.
